definitions:
  dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  dto.PingRequest:
    properties:
      text:
        type: string
    type: object
  dto.PingResponse:
    properties:
      message:
        type: string
    type: object
  models.PingPong:
    properties:
      text:
        description: ID   bson.ObjectId `bson:"_id,omitempty" json:"id"`
        type: string
    type: object
info:
  contact: {}
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: Get ping pong health api
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PingResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get ping pong health
      tags:
      - pingpong
    post:
      consumes:
      - application/json
      description: Create a new Ping Pong entry
      parameters:
      - description: Ping Pong text
        in: body
        name: text
        required: true
        schema:
          $ref: '#/definitions/dto.PingRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.PingResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Create a new Ping Pong entry
      tags:
      - pingpong
  /ping/{id}:
    delete:
      consumes:
      - application/json
      description: Delete ping by ID
      parameters:
      - description: Ping ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PingResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Delete ping by ID
      tags:
      - pingpong
    get:
      consumes:
      - application/json
      description: Get ping by ID
      parameters:
      - description: Ping ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PingPong'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get ping by ID
      tags:
      - pingpong
    put:
      consumes:
      - application/json
      description: Update ping by ID
      parameters:
      - description: Ping ID
        in: path
        name: id
        required: true
        type: string
      - description: Ping data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.PingRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PingResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Update ping by ID
      tags:
      - pingpong
  /ping/all:
    get:
      consumes:
      - application/json
      description: Get all Ping Pong entries
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.PingPong'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get all Ping Pong entries
      tags:
      - pingpong
swagger: "2.0"
